# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'MDW' do
  pod 'AFNetworking', '~> 3.0'
  pod 'Realm' , '~> 2.3.0’
  pod 'ZXingObjC', '~> 3.2.1'

end
